CHANGEABLE_FILE_TYPES = ('.swift',  '.xcodeproj')


ABBREVIATIONS = {
    "VC": "ViewController",
    "VM": "ViewModel",
    "API": "ApplicationProgrammingInterface",
    "HTTP": "HyperTextTransferProtocol",
    "URL": "UniformResourceLocator",
    "JSON": "JavaScriptObjectNotation",
    "ID": "Identifier",
    "HTML": "HyperTextMarkupLanguage",
    "UI": "UserInterface",
    "SDK": "SoftwareDevelopmentKit",
    "DB": "Database",
    "GUI": "GraphicalUserInterface",
    "XML": "ExtensibleMarkupLanguage",
    "CPU": "CentralProcessingUnit",
    "RAM": "RandomAccessMemory",
    "GPU": "GraphicsProcessingUnit",
    "IDE": "IntegratedDevelopmentEnvironment",
    "NS": "NextStep",
    "RGBA": "RedGreenBlueAlpha",
    "TCP": "TransmissionControlProtocol",
    "UDP": "UserDatagramProtocol",
    "ASCII": "AmericanStandardCodeForInformationInterchange",
    "HTTPS": "HyperTextTransferProtocolSecure",
    "LAN": "LocalAreaNetwork",
    "WLAN": "WirelessLocalAreaNetwork",
    "CSS": "CascadingStyleSheets",
    "MVC": "ModelViewController",
    "MVVM": "ModelViewViewModel",
    "VIPER": "ViewInteractorPresenterEntityRouter",
    "RxSwift": "ReactiveSwift",
    "CSV": "CommaSeparatedValues",
    "IB": "InterfaceBuilder",
    "XIB": "XMLInterfaceBuilder",
    "FPS": "FramesPerSecond",
    "SSL": "SecureSocketsLayer",
    "TLS": "TransportLayerSecurity",
    "OOP": "ObjectOrientedProgramming",
    "JWT": "JSONWebToken",
    "ORM": "ObjectRelationalMapping",
    "CLI": "CommandLineInterface",
    "QA": "QualityAssurance",
    "UX": "UserExperience",
    "REST": "RepresentationalStateTransfer",
    "TV": "TableView",
    "BG": "Background",
    "FG": "Foreground",
    "CIDR": "ClasslessInter-DomainRouting",
    "DNS": "DomainNameSystem",
    "FTP": "FileTransferProtocol",
    "SSH": "SecureShell",
    "VPN": "VirtualPrivateNetwork",
    "WAN": "WideAreaNetwork",
    "GCD": "GrandCentralDispatch",
    "NST": "NextStepTechnology",
    "XMLRPC": "XMLRemoteProcedureCall",
    "JSONRPC": "JSONRemoteProcedureCall",
    "SQL": "StructuredQueryLanguage",
    "CRUD": "CreateReadUpdateDelete",
    "CI": "ContinuousIntegration",
    "CD": "ContinuousDelivery",
    "VCS": "VersionControlSystem",
    "SCM": "SourceCodeManagement",
    "iOS": "iPhoneOperatingSystem",
    "macOS": "MacintoshOperatingSystem",
    "OSX": "OperatingSystemX",
}


ADJECTIVES = ['My', 'New', 'Alternative', 'Custom', 'Awesome', 'Cool', 'Nice',
              'Different', 'Unique', 'Special', 'Advanced', 'Modern', 'Simple', 'Basic',
              'Swift', 'Fancy', 'Other', 'Another', 'Top', 'Variant', 'Adapted', 'Customized',
              'Personalized', 'Personal', 'Private', 'Public', 'Open', 'Closed', 'Internal',
              'External', 'Global', 'Local', 'Static', 'Dynamic', 'Abstract', 'Final', 'Alt']


ALPHABET = 'abcdefghijklmnopqrstuvwxyz'
