CHANGEABLE_FILE_TYPES = ('.swift', '.xml', '.xib', '.storyboard', '.xcodeproj')

# FRAMEWORKS = ['FirebaseCoreInternal', 'FirebaseCore', 'Gifu', 'SwiftyDropbox', 'AlamofireNetworkActivityIndicator', 'AVFoundation', 'SDWebImage', 'CoreServices', 'Uniform Type Identifiers (UTIs)', 'SwiftyBeaver', 'FirebaseRemoteConfig', 'LocalAuthentication', 'R.swift', 'SnapKit', 'EventKit', 'Moya', 'ModelIO', 'CoreMotion', 'Socket.IO-Client-Swift', 'Foundation', 'Social', 'AlamofireObjectMapper', 'SpriteKit', 'Network', 'NotificationCenter', 'WatchConnectivity', 'AlamofireCore', 'CoreAnimation', 'Photos', 'WebKit', 'IQKeyboardManager', 'AdSupport', 'OHHTTPStubs', 'GCDWebServer', 'ObjectMapper', 'AuthenticationServices', 'PKHUD', 'CoreNFC', 'FirebaseAppDistribution', 'CoreFoundation', 'AlamofireXMLRPC', 'MediaPlayer', 'GameController', 'FirebaseCrashlytics', 'PDFKit', 'OAuthSwift', 'CoreMedia', 'SwiftMessages', 'HomeKit', 'FileProvider', 'PushKit', 'PhotosUI', 'CoreVideo', 'CloudKit', 'AlamofireNetworkReachability', 'SwiftKeychainWrapper', 'Nimble', 'FirebaseABTesting', 'Firebase', 'FirebasePredictions', 'RealmSwift', 'CoreText', 'Starscream', 'QuartzCore', 'Speech', 'Combine', 'SwiftUI', 'Accessibility', 'HealthKit', 'ReplayKit', 'CoreMIDI', 'FirebaseMLKit', 'Realm', 'FirebaseInAppMessaging', 'FirebaseDynamicLinks', 'SwiftWebSocket', 'FirebaseStorage', 'FSPagerView', 'IGListKit', 'CryptoSwift', 'Zip', 'CoreHaptics', 'MapKit', 'HanekeSwift', 'Cosmos', 'Hue', 'CoreData', 'StoreKit', 'LinkPresentation', 'MessageUI', 'PromiseKit', 'FirebaseRealtimeDatabase', 'FirebaseMessaging', 'UserNotifications', 'ARKit', 'Charts', 'Hero', 'CoreBluetooth', 'SwiftyJSON', 'CountryPickerView', 'SafariServices', 'Quick', 'FirebaseAppIndexing', 'Lottie', 'FirebaseTestLab', 'Eureka', 'CoreAudio', 'Alamofire', 'SceneKit', 'AFNetworking', 'CallKit', 'QuickLook', 'Contacts', 'Media Player', 'CoreGraphics', 'MetalKit', 'Promises', 'AudioToolbox', 'CoreML', 'SwiftLint', 'FirebaseFirestore', 'Intents', 'Gaming', 'CoreTelephony', 'FirebaseAuth', 'SQLite.swift', 'FirebasePerformance', 'SkyFloatingLabelTextField', 'NVActivityIndicatorView', 'Accelerate', 'CryptoKit', 'Onboard', 'ExternalAccessory', 'CoreLocation', 'Metal', 'URLSession', 'JWTDecode', 'Kingfisher', 'Vapor', 'ReSwift', 'WatchKit', 'RxDataSources', 'RxSwift', 'NotificationView', 'VideoToolbox', 'MediaAccessibility', 'SkeletonView', 'FirebaseCloudFunctions', 'FirebaseUI', 'KeychainSwift', 'Natural Language', 'FirebaseAppCheck', 'AlamofireImage', 'FirebaseAnalytics', 'UIKit', 'NotificationBanner', 'Result', 'Vision', 'SwiftyUserDefaults', 'AVKit', 'PassKit', 'MultipeerConnectivity', 'System', 'SwiftyStoreKit', 'XCTest', 'SwiftGen', 'SwiftDate', 'CoreImage', 'CoreSpotlight', 'GameplayKit', 'CoreAudioKit', 'MetalPerformanceShaders', 'UserInterface']
# FRAMEWORKS = [
#     "Alamofire",
#     "SwiftyJSON",
#     "AlamofireImage",
#     "Kingfisher",
#     "SnapKit",
#     "RxSwift",
#     "Realm",
#     "SwiftyUserDefaults",
#     "SwiftLint",
#     "Hero",
#     "Charts",
#     "NVActivityIndicatorView",
#     "SwiftyBeaver",
#     "SwiftGen",
#     "Moya",
#     "ObjectMapper",
#     "Firebase",
#     "Eureka",
#     "Quick",
#     "AlamofireNetworkActivityIndicator",
#     "PKHUD",
#     "Lottie",
#     "PromiseKit",
#     "SwiftDate",
#     "Result",
#     "ObjectMapper",
#     "AlamofireObjectMapper",
#     "RxDataSources",
#     "AlamofireNetworkActivityIndicator",
#     "PKHUD",
#     "Lottie",
#     "PromiseKit",
#     "SwiftDate",
#     "Result",
#     "ObjectMapper",
#     "AlamofireObjectMapper",
#     "RxDataSources",
#     "AlamofireNetworkActivityIndicator",
#     "PKHUD",
#     "Lottie",
#     "PromiseKit",
#     "SwiftDate",
#     "Result",
#     "ObjectMapper",
#     "AlamofireObjectMapper",
#     "RxDataSources",
#     "HanekeSwift",
#     "NVActivityIndicatorView",
#     "SnapKit",
#     "Quick",
#     "Gifu",
#     "SwiftyDropbox",
#     "SwiftyStoreKit",
# ]

ABBREVIATIONS = {
    "VC": "ViewController",
    "VM": "ViewModel",
    "API": "ApplicationProgrammingInterface",
    "HTTP": "HyperTextTransferProtocol",
    "URL": "UniformResourceLocator",
    "JSON": "JavaScriptObjectNotation",
    "ID": "Identifier",
    "HTML": "HyperTextMarkupLanguage",
    "UI": "UserInterface",
    "SDK": "SoftwareDevelopmentKit",
    "DB": "Database",
    "GUI": "GraphicalUserInterface",
    "XML": "ExtensibleMarkupLanguage",
    "CPU": "CentralProcessingUnit",
    "RAM": "RandomAccessMemory",
    "GPU": "GraphicsProcessingUnit",
    "IDE": "IntegratedDevelopmentEnvironment",
    "NS": "NextStep",
    "RGBA": "RedGreenBlueAlpha",
    "TCP": "TransmissionControlProtocol",
    "UDP": "UserDatagramProtocol",
    "ASCII": "AmericanStandardCodeForInformationInterchange",
    "HTTPS": "HyperTextTransferProtocolSecure",
    "LAN": "LocalAreaNetwork",
    "WLAN": "WirelessLocalAreaNetwork",
    "CSS": "CascadingStyleSheets",
    "MVC": "ModelViewController",
    "MVVM": "ModelViewViewModel",
    "VIPER": "ViewInteractorPresenterEntityRouter",
    "RxSwift": "ReactiveSwift",
    "CSV": "CommaSeparatedValues",
    "IB": "InterfaceBuilder",
    "XIB": "XMLInterfaceBuilder",
    "FPS": "FramesPerSecond",
    "SSL": "SecureSocketsLayer",
    "TLS": "TransportLayerSecurity",
    "OOP": "ObjectOrientedProgramming",
    "JWT": "JSONWebToken",
    "ORM": "ObjectRelationalMapping",
    "CLI": "CommandLineInterface",
    "QA": "QualityAssurance",
    "UX": "UserExperience",
    "REST": "RepresentationalStateTransfer",
    "TV": "TableView",
    "BG": "Background",
    "FG": "Foreground",
    "CIDR": "ClasslessInter-DomainRouting",
    "DNS": "DomainNameSystem",
    "FTP": "FileTransferProtocol",
    "SSH": "SecureShell",
    "VPN": "VirtualPrivateNetwork",
    "WAN": "WideAreaNetwork",
    "GCD": "GrandCentralDispatch",
    "NST": "NextStepTechnology",
    "XMLRPC": "XMLRemoteProcedureCall",
    "JSONRPC": "JSONRemoteProcedureCall",
    "SQL": "StructuredQueryLanguage",
    "CRUD": "CreateReadUpdateDelete",
    "CI": "ContinuousIntegration",
    "CD": "ContinuousDelivery",
    "VCS": "VersionControlSystem",
    "SCM": "SourceCodeManagement",
    "iOS": "iPhoneOperatingSystem",
    "macOS": "MacintoshOperatingSystem",
    "OSX": "OperatingSystemX",
}


ADJECTIVES = ['My', 'New', 'Alternative', 'Custom', 'Awesome', 'Cool', 'Nice',
              'Different', 'Unique', 'Special', 'Advanced', 'Modern', 'Simple', 'Basic',
              'Swift', 'Fancy', 'Other', 'Another', 'Top', 'Variant', 'Adapted', 'Customized',
              'Personalized', 'Personal', 'Private', 'Public', 'Open', 'Closed', 'Internal',
              'External', 'Global', 'Local', 'Static', 'Dynamic', 'Abstract', 'Final', 'Alt']


ALPHABET = 'abcdefghijklmnopqrstuvwxyz'
